name: Update README

on:
  schedule:
    # Se ejecuta cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Update Profile README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Recent Activity
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN || secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAME: SrDark04
